package com.example.ui.theme

import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color

// ======================================================================
// 1. STUDENT OS DARK VELVET & DEEP SPACE BACKGROUND PALETTE
// ======================================================================
val DarkVelvetCanvas = Color(0xFF07090E)        // Master deep space background (#07090E)
val DeepNavyBlack = Color(0xFF0A0E1A)          // Rich deep navy-black canvas
val DeepSpacePaper = Color(0xFF0E1322)         // Container paper layer
val OledCanvasBlack = Color(0xFF07090E)        // Pure OLED dark canvas
val OledCardDark = Color(0xFF111625)           // Dark opaque fallback surface
val OledCardSurface = Color(0xFF111625)        // Surface color
val OledSurfaceElevated = Color(0xFF182035)    // Elevated layer
val OledBorderGlow = Color(0x33C0CD8C)         // Subtle glow edge

// ===== Student OS — Light Tokens (Generated by Theme Lab) =====
val LightCanvas = Color(0xFFF8FAFC)
val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFF1F5F9)
val LightInk = Color(0xFF0F172A)
val LightInkSoft = Color(0xFF475569)
val LightOutline = Color(0xFFE2E8F0)

val LightPrimary = Color(0xFF2563EB)
val LightSecondary = Color(0xFF059669)
val LightTertiary = Color(0xFF6D4DCC)
val LightAmber = Color(0xFFD97706)
val LightError = Color(0xFFE11D48)

// StudentOsGlassTokens (rgba alpha-based)
val glassPrimary = Color(0xEBFFFFFF)       // surface @ 92%
val glassElevated = Color(0xFFFFFFFF)      // surface @ 100%
val borderLight = Color(0x14000000)       // subtle border @ 8%

// ======================================================================
// 2. GLASSMORPHISM 2.0 SURFACE & BORDER TOKENS
// ======================================================================
// Glass Surfaces (Semi-transparent rgba(22, 28, 45, 0.70) etc.)
val GlassSurfaceDark = Color(0xB3161C2D)       // rgba(22, 28, 45, 0.70)
val GlassSurfaceElevated = Color(0xCC1A233A)   // rgba(26, 35, 58, 0.80)
val GlassSurfaceSubtle = Color(0x66161C2D)     // rgba(22, 28, 45, 0.40)
val GlassSurfaceHighlight = Color(0x1FFFFFFF)  // Ultra-light glass sheen
val GlassWhiteBorder = Color(0x2EFFFFFF)       // 1px subtle white glass border
val GlassWhiteBorderFaint = Color(0x12FFFFFF)  // Faint border edge
val GlassDarkBorder = Color(0x14000000)        // Dark backdrop border

// Glass Highlight Border Gradients (1px linear gradient: white alpha -> 0)
val GlassBorderGradient = Brush.linearGradient(
    colors = listOf(Color.White.copy(alpha = 0.24f), Color.White.copy(alpha = 0.04f))
)
val GlassBorderHighlightGradient = Brush.linearGradient(
    colors = listOf(Color.White.copy(alpha = 0.38f), Color.White.copy(alpha = 0.08f))
)

// Colored Glass Border Gradients
val GlassCyanBorderGradient = Brush.linearGradient(
    colors = listOf(Color(0xFF06B6D4).copy(alpha = 0.55f), Color(0xFF06B6D4).copy(alpha = 0.08f))
)
val GlassEmeraldBorderGradient = Brush.linearGradient(
    colors = listOf(Color(0xFF10B981).copy(alpha = 0.55f), Color(0xFF10B981).copy(alpha = 0.08f))
)
val GlassPurpleBorderGradient = Brush.linearGradient(
    colors = listOf(Color(0xFFCBBEFF).copy(alpha = 0.55f), Color(0xFFCBBEFF).copy(alpha = 0.08f))
)

// ======================================================================
// 3. STUDENT OS SIGNATURE ACCENTS: CYAN, EMERALD, PURPLE, BLUE, AMBER
// ======================================================================
// Cyan & Sky / Neon Teal (AI & Course Workspace)
val CyberCyan = Color(0xFF06B6D4)              // Electric Cyan #06B6D4
val CyanNeon = Color(0xFF22D3EE)               // Radiant Cyan 400
val CyanGlow = Color(0xFF38BDF8)               // Sky Cyan Accent
val NeonTeal = Color(0xFF0D9488)               // Teal #0D9488
val CyanSoftBg = Color(0x1F06B6D4)             // Subtle Cyan Glass Wash

// Emerald & Mint (Attendance Safe / Passed Units / Success)
val EmeraldNeon = Color(0xFF10B981)            // Emerald Neon #10B981
val EmeraldGlow = Color(0xFF34D399)            // Vibrant Mint 400
val Emerald50 = Color(0xFFECFDF5)
val Emerald100 = Color(0xFFD1FAE5)
val Emerald500 = Color(0xFF10B981)
val Emerald600 = Color(0xFF059669)
val Emerald700 = Color(0xFF047857)
val EmeraldSoftBg = Color(0x1F10B981)          // Emerald Glass Wash

// Cyber Violet & Royal Purple (GPA / Honors / AI Analysis)
val CyberViolet = Color(0xFFCBBEFF)            // Cyber Violet #C0CD8C
val VioletNeon = Color(0xFFCBBEFF)             // Neon Purple #C0CD8C
val PurpleNeon = Color(0xFFCBBEFF)             // Purple 400
val PurpleSoftBg = Color(0x1FC0CD8C)           // Purple Glass Wash

// Electric Blue & Indigo (Hero Identity & Focus)
val ElectricBlueHero = Color(0xFF1D4ED8)       // Electric Blue #1D4ED8
val ElectricBlueAccent = Color(0xFF2563EB)     // Royal Blue #2563EB
val BrandIndigo50 = Color(0xFFEEF2FF)
val BrandIndigo100 = Color(0xFFE0E7FF)
val BrandIndigo200 = Color(0xFFC7D2FE)
val BrandIndigo400 = Color(0xFF818CF8)
val BrandIndigo500 = Color(0xFFCBBEFF)
val BrandIndigo600 = Color(0xFF6D4DCC)
val BrandIndigo700 = Color(0xFF6D4DCC)
val BrandIndigo900 = Color(0xFF38305B)

// Amber (Attendance Warning / Deadlines / Midterms)
val AmberGlow = Color(0xFFF59E0B)              // Amber #F59E0B
val AmberNeon = Color(0xFFFBBF24)              // Amber 400 #FBBF24
val Amber50 = Color(0xFFFFFBEB)
val Amber100 = Color(0xFFFEF3C7)
val Amber500 = Color(0xFFF59E0B)
val Amber600 = Color(0xFFD97706)
val AmberSoftBg = Color(0x1FF59E0B)            // Amber Glass Wash

// Crimson Rose (Critical Absence / Drop / Danger)
val CrimsonRose = Color(0xFFF43F5E)            // Crimson Rose #F43F5E
val RoseNeon = Color(0xFFFB7185)               // Rose 400 #FB7185
val Rose50 = Color(0xFFFFF1F2)
val Rose100 = Color(0xFFFFE4E6)
val Rose500 = Color(0xFFF43F5E)
val Rose600 = Color(0xFFE11D48)
val RoseSoftBg = Color(0x1FF43F5E)             // Rose Glass Wash

// Sky Blue
val Sky50 = Color(0xFFF0F9FF)
val Sky100 = Color(0xFFE0F2FE)
val Sky500 = Color(0xFF0EA5E9)
val Sky600 = Color(0xFF0284C7)

// Slate Neutrals
val Slate50 = Color(0xFFF8FAFC)
val Slate100 = Color(0xFFF1F5F9)
val Slate200 = Color(0xFFE2E8F0)
val Slate300 = Color(0xFFCBD5E1)
val Slate400 = Color(0xFFA69CBD)
val Slate500 = Color(0xFF64748B)
val Slate600 = Color(0xFF475569)
val Slate700 = Color(0xFF334155)
val Slate800 = Color(0xFF1E293B)
val Slate900 = Color(0xFF0F172A)

// Specialized Tags & Hero Gradients
val NotionTagSpecialized = Color(0xFFEEF2FF)
val NotionTagSpecializedDark = Color(0xFF282F48)
val NotionTagLab = Color(0xFFECFDF5)
val NotionTagLabDark = Color(0xFF1B382B)
val NotionTagBase = Color(0xFFFFFBEB)
val NotionTagBaseDark = Color(0xFF382F18)
val NotionTagGeneral = Color(0xFFF0ECF8)
val NotionTagGeneralDark = Color(0xFF38305B)
val RevolutCardGradientStart = Color(0xFF141926)
val RevolutCardGradientEnd = Color(0xFF0D101A)
val AppleDynamicPillBg = Color(0xEB161C2D)
val ApplePillBorder = Color(0x2EFFFFFF)

// Signature Gradients
val HeroPassportGradient = Brush.linearGradient(
    colors = listOf(Color(0xFF1D4ED8), Color(0xFF0284C7), Color(0xFF0D9488))
)
val CopilotCyberGradient = Brush.horizontalGradient(
    colors = listOf(Color(0xFFCBBEFF), Color(0xFF06B6D4))
)
val EmeraldProgressGradient = Brush.horizontalGradient(
    colors = listOf(Color(0xFF059669), Color(0xFF10B981), Color(0xFF34D399))
)

// ==========================================
// Bento 2026 Student OS Canonical Design Tokens
// ==========================================
// Light Mode Tokens
val BentoLightCanvas = Color(0xFFF8FAFC)
val BentoLightPaper = Color(0xFFF1F5F9)
val BentoLightSurface = Color(0xFFFFFFFF)
val BentoLightSurface2 = Color(0xFFF1F5F9)
val BentoLightInk = Color(0xFF0F172A)
val BentoLightInkSoft = Color(0xFF475569)
val BentoLightInkFaint = Color(0xFFA69CBD)
val BentoLightLine = Color(0xFFE2E8F0)
val BentoLightIndigo = Color(0xFF6D4DCC)
val BentoLightIndigoStrong = Color(0xFF38305B)
val BentoLightIndigoSoft = Color(0xFFEEF2FF)
val BentoLightAmber = Color(0xFFD97706)
val BentoLightAmberInk = Color(0xFF78350F)
val BentoLightAmberSoft = Color(0xFFFEF3C7)
val BentoLightMint = Color(0xFF059669)
val BentoLightMintSoft = Color(0xFFD1FAE5)
val BentoLightCoral = Color(0xFFE11D48)
val BentoLightCoralSoft = Color(0xFFFFE4E6)
val BentoLightSky = Color(0xFF0284C7)
val BentoLightSkySoft = Color(0xFFE0F2FE)

// Dark Mode Tokens
val BentoDarkCanvas = Color(0xFF07090E)
val BentoDarkPaper = Color(0xFF0E1322)
val BentoDarkSurface = Color(0xFF161C2D)
val BentoDarkSurface2 = Color(0xFF1C2438)
val BentoDarkInk = Color(0xFFEEF0F6)
val BentoDarkInkSoft = Color(0xFF9FA8BD)
val BentoDarkInkFaint = Color(0xFF6D7690)
val BentoDarkLine = Color(0xFF28324D)
val BentoDarkIndigo = Color(0xFFCBBEFF)
val BentoDarkIndigoStrong = Color(0xFF38305B)
val BentoDarkIndigoSoft = Color(0xFF38305B)
val BentoDarkAmber = Color(0xFFF0B054)
val BentoDarkAmberInk = Color(0xFFF5CD8E)
val BentoDarkAmberSoft = Color(0xFF332411)
val BentoDarkMint = Color(0xFF4FD5A6)
val BentoDarkMintSoft = Color(0xFF12301F)
val BentoDarkCoral = Color(0xFFF0897A)
val BentoDarkCoralSoft = Color(0xFF3A1D18)
val BentoDarkSky = Color(0xFF79A8F2)
val BentoDarkSkySoft = Color(0xFF182A46)

// Canonical identity: lavender on cool light surfaces; petrol/navy at night.
val AcademicNavy = Color(0xFF1E3A5F)
val AcademicNavyDark = Color(0xFF0F2338)
// Legacy names retained for source compatibility across existing screens.
val AcademicOlive = Color(0xFF6D4DCC)
val AcademicOliveLight = Color(0xFFCBBEFF)

val StudentPrimaryLight = Color(0xFF6D4DCC)
val StudentPrimaryContainerLight = Color(0xFFEDE6FF)
val StudentOnPrimaryContainerLight = Color(0xFF38246D)
val StudentSecondaryLight = Color(0xFF547998)
val StudentSecondaryContainerLight = Color(0xFFE4EDF5)
val StudentOnSecondaryContainerLight = Color(0xFF183249)
val StudentTertiaryLight = Color(0xFF855C20)
val StudentTertiaryContainerLight = Color(0xFFFFECCD)
val StudentOnTertiaryContainerLight = Color(0xFF412D0E)
val StudentErrorLight = Color(0xFFB32642)
val StudentErrorContainerLight = Color(0xFFFFE1E8)
val StudentOnErrorContainerLight = Color(0xFF680C26)
val StudentCanvasLight = Color(0xFFF7F5FC)
val StudentOnCanvasLight = Color(0xFF252137)
val StudentSurfaceLight = Color(0xFFFFFFFF)
val StudentOnSurfaceLight = Color(0xFF252137)
val StudentSurfaceVariantLight = Color(0xFFF0ECF8)
val StudentOnSurfaceVariantLight = Color(0xFF736D83)
val StudentOutlineLight = Color(0xFF817A91)
val StudentOutlineVariantLight = Color(0xFFE7E1F0)

val StudentPrimaryDark = Color(0xFFCBBEFF)
val StudentPrimaryContainerDark = Color(0xFF38305B)
val StudentOnPrimaryContainerDark = Color(0xFFE9E0FF)
val StudentSecondaryDark = Color(0xFFA8D8DF)
val StudentSecondaryContainerDark = Color(0xFF254555)
val StudentOnSecondaryContainerDark = Color(0xFFD9EDF8)
val StudentTertiaryDark = Color(0xFFE7C58F)
val StudentTertiaryContainerDark = Color(0xFF503B1E)
val StudentOnTertiaryContainerDark = Color(0xFFFFECCD)
val StudentErrorDark = Color(0xFFFFB2C0)
val StudentErrorContainerDark = Color(0xFF642036)
val StudentOnErrorContainerDark = Color(0xFFFFD9E2)
val StudentCanvasDark = Color(0xFF0C1B25)
val StudentOnCanvasDark = Color(0xFFE8EFF5)
val StudentSurfaceDark = Color(0xFF142936)
val StudentOnSurfaceDark = Color(0xFFE8EFF5)
val StudentSurfaceVariantDark = Color(0xFF203847)
val StudentOnSurfaceVariantDark = Color(0xFFB5C5D2)
val StudentOutlineDark = Color(0xFF8498A7)
val StudentOutlineVariantDark = Color(0xFF304957)
