package com.example.ui.components

import android.app.Activity
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.NoCredentialException
import com.example.R
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential

/**
 * Google account picker for Firebase Authentication.
 *
 * Uses the OAuth Web Client ID generated by Firebase. We first prefer an
 * already-authorized account and, if none exists, retry with the full account
 * picker so first-time users can choose any Google account.
 */
object GoogleSignInManager {

    suspend fun getIdToken(activity: Activity): Result<String> {
        return try {
            requestToken(activity, preferAuthorized = true)
        } catch (cancelled: GetCredentialCancellationException) {
            Result.failure(cancelled)
        } catch (noCredential: NoCredentialException) {
            requestToken(activity, preferAuthorized = false)
        } catch (firstAttemptError: Exception) {
            // A first-attempt account filter can fail on some Play Services
            // combinations; retry once with the general account picker.
            try {
                requestToken(activity, preferAuthorized = false)
            } catch (secondAttemptError: Exception) {
                Result.failure(secondAttemptError)
            }
        }
    }

    private suspend fun requestToken(
        activity: Activity,
        preferAuthorized: Boolean
    ): Result<String> {
        val googleIdOption = GetGoogleIdOption.Builder()
            .setServerClientId(activity.getString(R.string.default_web_client_id))
            .setFilterByAuthorizedAccounts(preferAuthorized)
            .setAutoSelectEnabled(false)
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(googleIdOption)
            .build()

        val credential = CredentialManager.create(activity)
            .getCredential(activity, request)
            .credential

        return if (
            credential is CustomCredential &&
            credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
        ) {
            Result.success(
                GoogleIdTokenCredential.createFrom(credential.data).idToken
            )
        } else {
            Result.failure(
                IllegalStateException("Google ID token credential was not returned.")
            )
        }
    }
}
